export const contentTypeTableDataSource = [
  {
    column0: "文件扩展名",
    column1: "Content-Type(Mime-Type)",
    column2: "文件扩展名",
    column3: "Content-Type(Mime-Type)",
  },
  {
    column0: ".*（ 二进制流，不知道下载文件类型）",
    column1: "application/octet-stream",
    column2: ".tif",
    column3: "image/tiff",
  },
  {
    column0: ".001",
    column1: "application/x-001",
    column2: ".301",
    column3: "application/x-301",
  },
  {
    column0: ".323",
    column1: "text/h323",
    column2: ".906",
    column3: "application/x-906",
  },
  {
    column0: ".907",
    column1: "drawing/907",
    column2: ".a11",
    column3: "application/x-a11",
  },
  {
    column0: ".acp",
    column1: "audio/x-mei-aac",
    column2: ".ai",
    column3: "application/postscript",
  },
  {
    column0: ".aif",
    column1: "audio/aiff",
    column2: ".aifc",
    column3: "audio/aiff",
  },
  {
    column0: ".aiff",
    column1: "audio/aiff",
    column2: ".anv",
    column3: "application/x-anv",
  },
  {
    column0: ".asa",
    column1: "text/asa",
    column2: ".asf",
    column3: "video/x-ms-asf",
  },
  {
    column0: ".asp",
    column1: "text/asp",
    column2: ".asx",
    column3: "video/x-ms-asf",
  },
  {
    column0: ".au",
    column1: "audio/basic",
    column2: ".avi",
    column3: "video/avi",
  },
  {
    column0: ".awf",
    column1: "application/vnd.adobe.workflow",
    column2: ".biz",
    column3: "text/xml",
  },
  {
    column0: ".bmp",
    column1: "application/x-bmp",
    column2: ".bot",
    column3: "application/x-bot",
  },
  {
    column0: ".c4t",
    column1: "application/x-c4t",
    column2: ".c90",
    column3: "application/x-c90",
  },
  {
    column0: ".cal",
    column1: "application/x-cals",
    column2: ".cat",
    column3: "application/vnd.ms-pki.seccat",
  },
  {
    column0: ".cdf",
    column1: "application/x-netcdf",
    column2: ".cdr",
    column3: "application/x-cdr",
  },
  {
    column0: ".cel",
    column1: "application/x-cel",
    column2: ".cer",
    column3: "application/x-x509-ca-cert",
  },
  {
    column0: ".cg4",
    column1: "application/x-g4",
    column2: ".cgm",
    column3: "application/x-cgm",
  },
  {
    column0: ".cit",
    column1: "application/x-cit",
    column2: ".class",
    column3: "java/*",
  },
  {
    column0: ".cml",
    column1: "text/xml",
    column2: ".cmp",
    column3: "application/x-cmp",
  },
  {
    column0: ".cmx",
    column1: "application/x-cmx",
    column2: ".cot",
    column3: "application/x-cot",
  },
  {
    column0: ".crl",
    column1: "application/pkix-crl",
    column2: ".crt",
    column3: "application/x-x509-ca-cert",
  },
  {
    column0: ".csi",
    column1: "application/x-csi",
    column2: ".css",
    column3: "text/css",
  },
  {
    column0: ".cut",
    column1: "application/x-cut",
    column2: ".dbf",
    column3: "application/x-dbf",
  },
  {
    column0: ".dbm",
    column1: "application/x-dbm",
    column2: ".dbx",
    column3: "application/x-dbx",
  },
  {
    column0: ".dcd",
    column1: "text/xml",
    column2: ".dcx",
    column3: "application/x-dcx",
  },
  {
    column0: ".der",
    column1: "application/x-x509-ca-cert",
    column2: ".dgn",
    column3: "application/x-dgn",
  },
  {
    column0: ".dib",
    column1: "application/x-dib",
    column2: ".dll",
    column3: "application/x-msdownload",
  },
  {
    column0: ".doc",
    column1: "application/msword",
    column2: ".dot",
    column3: "application/msword",
  },
  {
    column0: ".drw",
    column1: "application/x-drw",
    column2: ".dtd",
    column3: "text/xml",
  },
  {
    column0: ".dwf",
    column1: "Model/vnd.dwf",
    column2: ".dwf",
    column3: "application/x-dwf",
  },
  {
    column0: ".dwg",
    column1: "application/x-dwg",
    column2: ".dxb",
    column3: "application/x-dxb",
  },
  {
    column0: ".dxf",
    column1: "application/x-dxf",
    column2: ".edn",
    column3: "application/vnd.adobe.edn",
  },
  {
    column0: ".emf",
    column1: "application/x-emf",
    column2: ".eml",
    column3: "message/rfc822",
  },
  {
    column0: ".ent",
    column1: "text/xml",
    column2: ".epi",
    column3: "application/x-epi",
  },
  {
    column0: ".eps",
    column1: "application/x-ps",
    column2: ".eps",
    column3: "application/postscript",
  },
  {
    column0: ".etd",
    column1: "application/x-ebx",
    column2: ".exe",
    column3: "application/x-msdownload",
  },
  {
    column0: ".fax",
    column1: "image/fax",
    column2: ".fdf",
    column3: "application/vnd.fdf",
  },
  {
    column0: ".fif",
    column1: "application/fractals",
    column2: ".fo",
    column3: "text/xml",
  },
  {
    column0: ".frm",
    column1: "application/x-frm",
    column2: ".g4",
    column3: "application/x-g4",
  },
  {
    column0: ".gbr",
    column1: "application/x-gbr",
    column2: ".",
    column3: "application/x-",
  },
  {
    column0: ".gif",
    column1: "image/gif",
    column2: ".gl2",
    column3: "application/x-gl2",
  },
  {
    column0: ".gp4",
    column1: "application/x-gp4",
    column2: ".hgl",
    column3: "application/x-hgl",
  },
  {
    column0: ".hmr",
    column1: "application/x-hmr",
    column2: ".hpg",
    column3: "application/x-hpgl",
  },
  {
    column0: ".hpl",
    column1: "application/x-hpl",
    column2: ".hqx",
    column3: "application/mac-binhex40",
  },
  {
    column0: ".hrf",
    column1: "application/x-hrf",
    column2: ".hta",
    column3: "application/hta",
  },
  {
    column0: ".htc",
    column1: "text/x-component",
    column2: ".htm",
    column3: "text/html",
  },
  {
    column0: ".html",
    column1: "text/html",
    column2: ".htt",
    column3: "text/webviewhtml",
  },
  {
    column0: ".htx",
    column1: "text/html",
    column2: ".icb",
    column3: "application/x-icb",
  },
  {
    column0: ".ico",
    column1: "image/x-icon",
    column2: ".ico",
    column3: "application/x-ico",
  },
  {
    column0: ".iff",
    column1: "application/x-iff",
    column2: ".ig4",
    column3: "application/x-g4",
  },
  {
    column0: ".igs",
    column1: "application/x-igs",
    column2: ".iii",
    column3: "application/x-iphone",
  },
  {
    column0: ".img",
    column1: "application/x-img",
    column2: ".ins",
    column3: "application/x-internet-signup",
  },
  {
    column0: ".isp",
    column1: "application/x-internet-signup",
    column2: ".IVF",
    column3: "video/x-ivf",
  },
  {
    column0: ".java",
    column1: "java/*",
    column2: ".jfif",
    column3: "image/jpeg",
  },
  {
    column0: ".jpe",
    column1: "image/jpeg",
    column2: ".jpe",
    column3: "application/x-jpe",
  },
  {
    column0: ".jpeg",
    column1: "image/jpeg",
    column2: ".jpg",
    column3: "image/jpeg",
  },
  {
    column0: ".jpg",
    column1: "application/x-jpg",
    column2: ".js",
    column3: "application/x-javascript",
  },
  {
    column0: ".jsp",
    column1: "text/html",
    column2: ".la1",
    column3: "audio/x-liquid-file",
  },
  {
    column0: ".lar",
    column1: "application/x-laplayer-reg",
    column2: ".latex",
    column3: "application/x-latex",
  },
  {
    column0: ".lavs",
    column1: "audio/x-liquid-secure",
    column2: ".lbm",
    column3: "application/x-lbm",
  },
  {
    column0: ".lmsff",
    column1: "audio/x-la-lms",
    column2: ".ls",
    column3: "application/x-javascript",
  },
  {
    column0: ".ltr",
    column1: "application/x-ltr",
    column2: ".m1v",
    column3: "video/x-mpeg",
  },
  {
    column0: ".m2v",
    column1: "video/x-mpeg",
    column2: ".m3u",
    column3: "audio/mpegurl",
  },
  {
    column0: ".m4e",
    column1: "video/mpeg4",
    column2: ".mac",
    column3: "application/x-mac",
  },
  {
    column0: ".man",
    column1: "application/x-troff-man",
    column2: ".math",
    column3: "text/xml",
  },
  {
    column0: ".mdb",
    column1: "application/msaccess",
    column2: ".mdb",
    column3: "application/x-mdb",
  },
  {
    column0: ".mfp",
    column1: "application/x-shockwave-flash",
    column2: ".mht",
    column3: "message/rfc822",
  },
  {
    column0: ".mhtml",
    column1: "message/rfc822",
    column2: ".mi",
    column3: "application/x-mi",
  },
  {
    column0: ".mid",
    column1: "audio/mid",
    column2: ".midi",
    column3: "audio/mid",
  },
  {
    column0: ".mil",
    column1: "application/x-mil",
    column2: ".mml",
    column3: "text/xml",
  },
  {
    column0: ".mnd",
    column1: "audio/x-musicnet-download",
    column2: ".mns",
    column3: "audio/x-musicnet-stream",
  },
  {
    column0: ".mocha",
    column1: "application/x-javascript",
    column2: ".movie",
    column3: "video/x-sgi-movie",
  },
  {
    column0: ".mp1",
    column1: "audio/mp1",
    column2: ".mp2",
    column3: "audio/mp2",
  },
  {
    column0: ".mp2v",
    column1: "video/mpeg",
    column2: ".mp3",
    column3: "audio/mp3",
  },
  {
    column0: ".mp4",
    column1: "video/mpeg4",
    column2: ".mpa",
    column3: "video/x-mpg",
  },
  {
    column0: ".mpd",
    column1: "application/vnd.ms-project",
    column2: ".mpe",
    column3: "video/x-mpeg",
  },
  {
    column0: ".mpeg",
    column1: "video/mpg",
    column2: ".mpg",
    column3: "video/mpg",
  },
  {
    column0: ".mpga",
    column1: "audio/rn-mpeg",
    column2: ".mpp",
    column3: "application/vnd.ms-project",
  },
  {
    column0: ".mps",
    column1: "video/x-mpeg",
    column2: ".mpt",
    column3: "application/vnd.ms-project",
  },
  {
    column0: ".mpv",
    column1: "video/mpg",
    column2: ".mpv2",
    column3: "video/mpeg",
  },
  {
    column0: ".mpw",
    column1: "application/vnd.ms-project",
    column2: ".mpx",
    column3: "application/vnd.ms-project",
  },
  {
    column0: ".mtx",
    column1: "text/xml",
    column2: ".mxp",
    column3: "application/x-mmxp",
  },
  {
    column0: ".net",
    column1: "image/pnetvue",
    column2: ".nrf",
    column3: "application/x-nrf",
  },
  {
    column0: ".nws",
    column1: "message/rfc822",
    column2: ".odc",
    column3: "text/x-ms-odc",
  },
  {
    column0: ".out",
    column1: "application/x-out",
    column2: ".p10",
    column3: "application/pkcs10",
  },
  {
    column0: ".p12",
    column1: "application/x-pkcs12",
    column2: ".p7b",
    column3: "application/x-pkcs7-certificates",
  },
  {
    column0: ".p7c",
    column1: "application/pkcs7-mime",
    column2: ".p7m",
    column3: "application/pkcs7-mime",
  },
  {
    column0: ".p7r",
    column1: "application/x-pkcs7-certreqresp",
    column2: ".p7s",
    column3: "application/pkcs7-signature",
  },
  {
    column0: ".pc5",
    column1: "application/x-pc5",
    column2: ".pci",
    column3: "application/x-pci",
  },
  {
    column0: ".pcl",
    column1: "application/x-pcl",
    column2: ".pcx",
    column3: "application/x-pcx",
  },
  {
    column0: ".pdf",
    column1: "application/pdf",
    column2: ".pdf",
    column3: "application/pdf",
  },
  {
    column0: ".pdx",
    column1: "application/vnd.adobe.pdx",
    column2: ".pfx",
    column3: "application/x-pkcs12",
  },
  {
    column0: ".pgl",
    column1: "application/x-pgl",
    column2: ".pic",
    column3: "application/x-pic",
  },
  {
    column0: ".pko",
    column1: "application/vnd.ms-pki.pko",
    column2: ".pl",
    column3: "application/x-perl",
  },
  {
    column0: ".plg",
    column1: "text/html",
    column2: ".pls",
    column3: "audio/scpls",
  },
  {
    column0: ".plt",
    column1: "application/x-plt",
    column2: ".png",
    column3: "image/png",
  },
  {
    column0: ".png",
    column1: "application/x-png",
    column2: ".pot",
    column3: "application/vnd.ms-powerpoint",
  },
  {
    column0: ".ppa",
    column1: "application/vnd.ms-powerpoint",
    column2: ".ppm",
    column3: "application/x-ppm",
  },
  {
    column0: ".pps",
    column1: "application/vnd.ms-powerpoint",
    column2: ".ppt",
    column3: "application/vnd.ms-powerpoint",
  },
  {
    column0: ".ppt",
    column1: "application/x-ppt",
    column2: ".pr",
    column3: "application/x-pr",
  },
  {
    column0: ".prf",
    column1: "application/pics-rules",
    column2: ".prn",
    column3: "application/x-prn",
  },
  {
    column0: ".prt",
    column1: "application/x-prt",
    column2: ".ps",
    column3: "application/x-ps",
  },
  {
    column0: ".ps",
    column1: "application/postscript",
    column2: ".ptn",
    column3: "application/x-ptn",
  },
  {
    column0: ".pwz",
    column1: "application/vnd.ms-powerpoint",
    column2: ".r3t",
    column3: "text/vnd.rn-realtext3d",
  },
  {
    column0: ".ra",
    column1: "audio/vnd.rn-realaudio",
    column2: ".ram",
    column3: "audio/x-pn-realaudio",
  },
  {
    column0: ".ras",
    column1: "application/x-ras",
    column2: ".rat",
    column3: "application/rat-file",
  },
  {
    column0: ".rdf",
    column1: "text/xml",
    column2: ".rec",
    column3: "application/vnd.rn-recording",
  },
  {
    column0: ".red",
    column1: "application/x-red",
    column2: ".rgb",
    column3: "application/x-rgb",
  },
  {
    column0: ".rjs",
    column1: "application/vnd.rn-realsystem-rjs",
    column2: ".rjt",
    column3: "application/vnd.rn-realsystem-rjt",
  },
  {
    column0: ".rlc",
    column1: "application/x-rlc",
    column2: ".rle",
    column3: "application/x-rle",
  },
  {
    column0: ".rm",
    column1: "application/vnd.rn-realmedia",
    column2: ".rmf",
    column3: "application/vnd.adobe.rmf",
  },
  {
    column0: ".rmi",
    column1: "audio/mid",
    column2: ".rmj",
    column3: "application/vnd.rn-realsystem-rmj",
  },
  {
    column0: ".rmm",
    column1: "audio/x-pn-realaudio",
    column2: ".rmp",
    column3: "application/vnd.rn-rn_music_package",
  },
  {
    column0: ".rms",
    column1: "application/vnd.rn-realmedia-secure",
    column2: ".rmvb",
    column3: "application/vnd.rn-realmedia-vbr",
  },
  {
    column0: ".rmx",
    column1: "application/vnd.rn-realsystem-rmx",
    column2: ".rnx",
    column3: "application/vnd.rn-realplayer",
  },
  {
    column0: ".rp",
    column1: "image/vnd.rn-realpix",
    column2: ".rpm",
    column3: "audio/x-pn-realaudio-plugin",
  },
  {
    column0: ".rsml",
    column1: "application/vnd.rn-rsml",
    column2: ".rt",
    column3: "text/vnd.rn-realtext",
  },
  {
    column0: ".rtf",
    column1: "application/msword",
    column2: ".rtf",
    column3: "application/x-rtf",
  },
  {
    column0: ".rv",
    column1: "video/vnd.rn-realvideo",
    column2: ".sam",
    column3: "application/x-sam",
  },
  {
    column0: ".sat",
    column1: "application/x-sat",
    column2: ".sdp",
    column3: "application/sdp",
  },
  {
    column0: ".sdw",
    column1: "application/x-sdw",
    column2: ".sit",
    column3: "application/x-stuffit",
  },
  {
    column0: ".slb",
    column1: "application/x-slb",
    column2: ".sld",
    column3: "application/x-sld",
  },
  {
    column0: ".slk",
    column1: "drawing/x-slk",
    column2: ".smi",
    column3: "application/smil",
  },
  {
    column0: ".smil",
    column1: "application/smil",
    column2: ".smk",
    column3: "application/x-smk",
  },
  {
    column0: ".snd",
    column1: "audio/basic",
    column2: ".sol",
    column3: "text/plain",
  },
  {
    column0: ".sor",
    column1: "text/plain",
    column2: ".spc",
    column3: "application/x-pkcs7-certificates",
  },
  {
    column0: ".spl",
    column1: "application/futuresplash",
    column2: ".spp",
    column3: "text/xml",
  },
  {
    column0: ".ssm",
    column1: "application/streamingmedia",
    column2: ".sst",
    column3: "application/vnd.ms-pki.certstore",
  },
  {
    column0: ".stl",
    column1: "application/vnd.ms-pki.stl",
    column2: ".stm",
    column3: "text/html",
  },
  {
    column0: ".sty",
    column1: "application/x-sty",
    column2: ".svg",
    column3: "text/xml",
  },
  {
    column0: ".swf",
    column1: "application/x-shockwave-flash",
    column2: ".tdf",
    column3: "application/x-tdf",
  },
  {
    column0: ".tg4",
    column1: "application/x-tg4",
    column2: ".tga",
    column3: "application/x-tga",
  },
  {
    column0: ".tif",
    column1: "image/tiff",
    column2: ".tif",
    column3: "application/x-tif",
  },
  {
    column0: ".tiff",
    column1: "image/tiff",
    column2: ".tld",
    column3: "text/xml",
  },
  {
    column0: ".top",
    column1: "drawing/x-top",
    column2: ".torrent",
    column3: "application/x-bittorrent",
  },
  {
    column0: ".tsd",
    column1: "text/xml",
    column2: ".txt",
    column3: "text/plain",
  },
  {
    column0: ".uin",
    column1: "application/x-icq",
    column2: ".uls",
    column3: "text/iuls",
  },
  {
    column0: ".vcf",
    column1: "text/x-vcard",
    column2: ".vda",
    column3: "application/x-vda",
  },
  {
    column0: ".vdx",
    column1: "application/vnd.visio",
    column2: ".vml",
    column3: "text/xml",
  },
  {
    column0: ".vpg",
    column1: "application/x-vpeg005",
    column2: ".vsd",
    column3: "application/vnd.visio",
  },
  {
    column0: ".vsd",
    column1: "application/x-vsd",
    column2: ".vss",
    column3: "application/vnd.visio",
  },
  {
    column0: ".vst",
    column1: "application/vnd.visio",
    column2: ".vst",
    column3: "application/x-vst",
  },
  {
    column0: ".vsw",
    column1: "application/vnd.visio",
    column2: ".vsx",
    column3: "application/vnd.visio",
  },
  {
    column0: ".vtx",
    column1: "application/vnd.visio",
    column2: ".vxml",
    column3: "text/xml",
  },
  {
    column0: ".wav",
    column1: "audio/wav",
    column2: ".wax",
    column3: "audio/x-ms-wax",
  },
  {
    column0: ".wb1",
    column1: "application/x-wb1",
    column2: ".wb2",
    column3: "application/x-wb2",
  },
  {
    column0: ".wb3",
    column1: "application/x-wb3",
    column2: ".wbmp",
    column3: "image/vnd.wap.wbmp",
  },
  {
    column0: ".wiz",
    column1: "application/msword",
    column2: ".wk3",
    column3: "application/x-wk3",
  },
  {
    column0: ".wk4",
    column1: "application/x-wk4",
    column2: ".wkq",
    column3: "application/x-wkq",
  },
  {
    column0: ".wks",
    column1: "application/x-wks",
    column2: ".wm",
    column3: "video/x-ms-wm",
  },
  {
    column0: ".wma",
    column1: "audio/x-ms-wma",
    column2: ".wmd",
    column3: "application/x-ms-wmd",
  },
  {
    column0: ".wmf",
    column1: "application/x-wmf",
    column2: ".wml",
    column3: "text/vnd.wap.wml",
  },
  {
    column0: ".wmv",
    column1: "video/x-ms-wmv",
    column2: ".wmx",
    column3: "video/x-ms-wmx",
  },
  {
    column0: ".wmz",
    column1: "application/x-ms-wmz",
    column2: ".wp6",
    column3: "application/x-wp6",
  },
  {
    column0: ".wpd",
    column1: "application/x-wpd",
    column2: ".wpg",
    column3: "application/x-wpg",
  },
  {
    column0: ".wpl",
    column1: "application/vnd.ms-wpl",
    column2: ".wq1",
    column3: "application/x-wq1",
  },
  {
    column0: ".wr1",
    column1: "application/x-wr1",
    column2: ".wri",
    column3: "application/x-wri",
  },
  {
    column0: ".wrk",
    column1: "application/x-wrk",
    column2: ".ws",
    column3: "application/x-ws",
  },
  {
    column0: ".ws2",
    column1: "application/x-ws",
    column2: ".wsc",
    column3: "text/scriptlet",
  },
  {
    column0: ".wsdl",
    column1: "text/xml",
    column2: ".wvx",
    column3: "video/x-ms-wvx",
  },
  {
    column0: ".xdp",
    column1: "application/vnd.adobe.xdp",
    column2: ".xdr",
    column3: "text/xml",
  },
  {
    column0: ".xfd",
    column1: "application/vnd.adobe.xfd",
    column2: ".xfdf",
    column3: "application/vnd.adobe.xfdf",
  },
  {
    column0: ".xhtml",
    column1: "text/html",
    column2: ".xls",
    column3: "application/vnd.ms-excel",
  },
  {
    column0: ".xls",
    column1: "application/x-xls",
    column2: ".xlw",
    column3: "application/x-xlw",
  },
  {
    column0: ".xml",
    column1: "text/xml",
    column2: ".xpl",
    column3: "audio/scpls",
  },
  {
    column0: ".xq",
    column1: "text/xml",
    column2: ".xql",
    column3: "text/xml",
  },
  {
    column0: ".xquery",
    column1: "text/xml",
    column2: ".xsd",
    column3: "text/xml",
  },
  {
    column0: ".xsl",
    column1: "text/xml",
    column2: ".xslt",
    column3: "text/xml",
  },
  {
    column0: ".xwd",
    column1: "application/x-xwd",
    column2: ".x_b",
    column3: "application/x-x_b",
  },
  {
    column0: ".sis",
    column1: "application/vnd.symbian.install",
    column2: ".sisx",
    column3: "application/vnd.symbian.install",
  },
  {
    column0: ".x_t",
    column1: "application/x-x_t",
    column2: ".ipa",
    column3: "application/vnd.iphone",
  },
  {
    column0: ".apk",
    column1: "application/vnd.android.package-archive",
    column2: ".xap",
    column3: "application/x-silverlight-app",
  },
];
